# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptMCMC <- function(X, beta, sigma) {
    .Call('_bmgpm_adaptMCMC', PACKAGE = 'bmgpm', X, beta, sigma)
}

mcmcmove <- function(p, sigma) {
    .Call('_bmgpm_mcmcmove', PACKAGE = 'bmgpm', p, sigma)
}

